make minimodem compile on Debian 12
Sadly we cannot include <fcntl.h> as that will conflict with
<linux/fcntl.h> but the latter doesn't declare the actual fcntl symbo :(

ttytdd/minimodem.c: In function ‘minimodem_run_tty_tx’:
ttytdd/minimodem.c:73:15: error: implicit declaration of function ‘fcntl’ [-Wimplicit-function-declaration]
   73 |     int ret = fcntl(child_write[0], F_SETPIPE_SZ, 160 * 4 * TTY_MINIMODEM_BUFFER_SIZE);
      |               ^~~~~
make[1]: *** [Makefile:665: ttytdd/minimodem.o] Error 1